'''
Assignment-1
problem-5.1
Akashdeep Roy
QR decomposition & to find eigenvalue using it & to compare with the eigenvalue generated by a library function
'''
#importing the library
import numpy as np
#input zone
A=np.array([[5,-2],[-2,8]]) #The matrix
err=0.0001  #Accuracy limit
#computation zone
temp= np.zeros((2,2),dtype=float)
W=np.zeros((2,2),dtype=float)
W = np.copy(A)
q=np.zeros((2,2),dtype=float)
s=1
while (s==1):
    temp = np.linalg.qr(W)
    q = np.dot(np.dot(np.transpose(temp[0]),W),temp[0])
    for i in range(2):
        for j in range(2):
            if (abs(q[i,j]-W[i,j])<err):
              s=0
    W=np.copy(q)
#output zone
print("eigenvalues computed via QR decomposition = ", q[0][0],q[1][1])
print("eigenvalues computed using inbuild library = ", np.linalg.eigvals(A))
print("They are matched upto the relative accuracy for the smaller one = ", (abs(q[0,0]-np.linalg.eigvals(A)[1])/np.linalg.eigvals(A)[1])*100,"%")
print("They are matched upto the relative accuracy for the larger one = ", (abs(q[1,1]-np.linalg.eigvals(A)[0])/np.linalg.eigvals(A)[0])*100,"%")